### ISSUE TITLE
Relaunch: must haves

### ISSUE THREAD

**Issue by katrin-k** [rubycorns/rorganize.it#488]
For the relaunch of the new design, I'd like to open this new issue where we can focus on the must-haves for the relaunch. It's an add-on for #468.
Feel free to reorder the list as deemed necessary. 

### Todos before relaunch:
- [x] Test the hell out of the page. 
- [x] Button pattern (somewhat consistent atm, but not really. Another button style might also be in order, especially to mark differences to tags.) (Katrin)
- [x] Check border on buttons that are `<input type="submit>`
- [x] All links need care. They currently don't match the design by Justine. (Katrin)
- [ ] Resposinvenes/ media queries
- [x] Check all files for "TODO"-comments: Here I mentioned when I had a problem somewhere 
- [ ] Rework welcome page
- [x] Alert messages
- [x] Profile page: display of the groups

### Todos during relaunch:
- [x] remove `appendRedesignParam()` from main.js 
- [x] remove all Bootstraps

### Todos right after relaunch:
- [ ] test the page for missing functionality (Bootstraps' JS might interfere beforehand)
- [ ] Tabbed content for groups#show

#### Nice-to-haves
The nice-to-have list has issues that are no deal-breakers and can be reassigned to separate issues later on. 
- [ ] Enhance form styling for error highlighting, focus states, etc.
- [ ] Check all files for missing accessibility markup
- [ ] Admin dashboard: functionality of the gif section

**Comment by berlintam** [comment]
@katrin-k here are my notes!

1. the profile page is a bit squishy, & also clicking the change password button doesn't do anything. Also the "working on" section doesn't seem to respect markdown anymore. 
<img width="1002" alt="screen shot 2016-11-15 at 20 32 50" src="https://cloud.githubusercontent.com/assets/4237285/20320650/d3d6d6d2-ab72-11e6-8aff-da106fe55a7d.png">

2. groups page fails if the markdown content is nil (ex: if group.activities or group.activities is empty).
<img width="1268" alt="screen shot 2016-11-15 at 20 42 10" src="https://cloud.githubusercontent.com/assets/4237285/20321023/475529f0-ab74-11e6-970e-762a453854f5.png">

3. top part of welcome page looks like an error, instead of just information. Maybe just changing the colour will help?  & GAAASP Captain Picard eating cake is gone!
<img width="1228" alt="screen shot 2016-11-15 at 20 45 18" src="https://cloud.githubusercontent.com/assets/4237285/20321095/81712c92-ab74-11e6-8f64-9dadbeb5b893.png">

4. blog page: there's not much space between the individual blogposts, maybe just a bottom margin is enough? 
<img width="809" alt="screen shot 2016-11-15 at 20 52 59" src="https://cloud.githubusercontent.com/assets/4237285/20321436/bcafe9f0-ab75-11e6-8a99-35af2c48e7d6.png">
Also the twitter feed on the right doesn't take up the whole side column (there's a lot of white space)
<img width="1237" alt="screen shot 2016-11-15 at 20 53 06" src="https://cloud.githubusercontent.com/assets/4237285/20321425/b6c197aa-ab75-11e6-9537-19dd986cebf1.png">

5. groups/new page has two cancel buttons. Also, info should be singular :)
<img width="460" alt="screen shot 2016-11-15 at 20 55 34" src="https://cloud.githubusercontent.com/assets/4237285/20321489/e8fcfdfe-ab75-11e6-9d0a-ec6f50eda69e.png">

K, that's the things I found that didn't have TODOs attached to them. Let me know if you need help/want me to do something/I dunno! Also, despite my comments, I think it looks super awesome & it looks like you're doing some cool css stuff that blows my mind. Thanks so much for tackling this!

**Comment by lislis** [comment]
Some nit picks
- The sub navigation is grey in the design. I think it's quite useful, otherwise everything is very white
![screen shot 2016-11-17 at 12 06 44](https://cloud.githubusercontent.com/assets/1006478/20387108/e329b47c-acbe-11e6-85ab-b334741ed10f.png)
(^ in browser quick edit)

- Moar spacing between these
![screen shot 2016-11-17 at 12 07 14](https://cloud.githubusercontent.com/assets/1006478/20387140/04a97e02-acbf-11e6-814f-8bc08e66adec.png)

- Moar spacing between main content and sidebar
![screen shot 2016-11-17 at 12 07 29](https://cloud.githubusercontent.com/assets/1006478/20387154/14b443c2-acbf-11e6-91c2-5bf4a3ac9eeb.png)

- remove navigation hover for sign in buttons.
![screen shot 2016-11-17 at 12 08 34](https://cloud.githubusercontent.com/assets/1006478/20387166/232bf738-acbf-11e6-97d3-369872a3a445.png)
I would style those more like buttons

**Comment by katrin-k** [comment]
@lislis I'm quite a bit unsure how to handle the sign-in buttons. I agree with removing the current hover-highlight. But the button-styles… I'm not sure.

Here's what I have so far. wdyt?
1) differentiating button styles in non-hover state
![screen shot 2016-11-24 at 3 34 09 pm](https://cloud.githubusercontent.com/assets/2246045/20602521/ecf5f750-b25d-11e6-95ad-641e74942850.png)

2) same button first in non-hover, then hover-state
![screen shot 2016-11-24 at 3 31 43 pm](https://cloud.githubusercontent.com/assets/2246045/20602539/08f71cfe-b25e-11e6-9e76-2a3b85c3cb24.png)
![screen shot 2016-11-24 at 3 31 54 pm](https://cloud.githubusercontent.com/assets/2246045/20602561/2575289e-b25e-11e6-9d04-caf028ff8afa.png)

3) no button in non-hover and full-color-button on hover
![screen shot 2016-11-24 at 3 54 35 pm](https://cloud.githubusercontent.com/assets/2246045/20602600/5a7dc96a-b25e-11e6-8a87-eba17c8230ac.png)
![screen shot 2016-11-24 at 3 31 27 pm](https://cloud.githubusercontent.com/assets/2246045/20602566/2b17f6f0-b25e-11e6-9340-bc5fac7394ef.png)

**Comment by lislis** [comment]
@katrin-k I'd go for number 3. Less things going when idling and clear what's going on on hover :)

**Comment by sareg0** [comment]
All these tasks are DONE-ZO! I'm going to close this issue up. @katrin-k thank you so much for you hard work in making the redesign happen. You're a Rubycorn-hero now and forever.
